apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pushwf
  labels: 
    name: "pushwf"
    # force policy will ensure that deployment is updated
    # even when tag is unchanged (latest remains)
    keel.sh/policy: force
    keel.sh/trigger: poll # <-- actively query registry, otherwise defaults to webhooks
  annotations:
    keel.sh/pollSchedule: "@every 10s"
    # keel.sh/notify: chan1,chan2
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pushwf
  template:
    metadata:
      name: pushwf
      labels:
        app: pushwf
    spec:     
      containers:                    
        - image: ghcr.io/atrakic/keel-demo:latest # localhost:5001/keel-demo:latest
          imagePullPolicy: Always # this is required to force pull image     
          name: pushwf
          ports:
            - containerPort: 8500
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8500
            initialDelaySeconds: 10
            timeoutSeconds: 5    
